name: Code Quality

on:
  push:
    branches: [ master ] # Adjust branches as needed
  pull_request:
    branches: [ master ] # Adjust branches as needed

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Setup Biome
        uses: biomejs/setup-biome@4c91541eaada48f67d7dbd7833600ce162b68f51 # v2.7.1
        with:
          version: latest
      - name: Run Biome
        run: biome ci ./src --reporter=github
